bpftune: disable stack protection for BPF objects
as reported in

https://github.com/oracle-samples/bpftune/issues/12

we see compilation failures like

tcp_buffer_tuner.bpf.c:232:1: error: A call to built-in function '__stack_chk_fail' is not supported.

this looks like [1], which is fixed by disabling stack
protection. Try this here too.

Reported-by: https://github.com/delvin-fil
Signed-off-by: Alan Maguire <alan.maguire@oracle.com>